My-Knockout-Bootstrap-MVC-Sample/Models/MTB_Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace My_Knockout_Bootstrap_MVC_Sample.Models
{
    public class MTB_Article
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Excerpts { get; set; }
        public string Content { get; set; }

    }
    public class MyTecBitsDBContext : DbContext
    {
        public DbSet<MTB_Article> MyTecBitsDB { get; set; }
    }
}

My-Knockout-Bootstrap-MVC-Sample/Controllers/MTB_ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using My_Knockout_Bootstrap_MVC_Sample.Models;

namespace My_Knockout_Bootstrap_MVC_Sample.Controllers
{
    public class MTB_ArticlesController : Controller
    {
        private MyTecBitsDBContext db = new MyTecBitsDBContext();

        //
        // GET: /MTB_Articles/

        public ActionResult Index()
        {
            return View(db.MyTecBitsDB.ToList());
        }

        //
        // GET: /MTB_Articles/Details/5

        public ActionResult Details(int id = 0)
        {
            MTB_Article mtb_article = db.MyTecBitsDB.Find(id);
            if (mtb_article == null)
            {
                return HttpNotFound();
            }
            return View(mtb_article);
        }

        //
        // GET: /MTB_Articles/Create

        public ActionResult Create()
        {
            return View();
        }

        public JsonResult FillIndex()
        {
            return Json(db.MyTecBitsDB.ToList(), JsonRequestBehavior.AllowGet);
        }

        //
        // POST: /MTB_Articles/Create

        [HttpPost]
        public String Create(MTB_Article mtb_article)
        {
            db.MyTecBitsDB.Add(mtb_article);
            db.SaveChanges();
            return "success";
        }

        //
        // GET: /MTB_Articles/Edit/5

        public ActionResult Edit(int id = 0)
        {
            MTB_Article mtb_article = db.MyTecBitsDB.Find(id);
            if (mtb_article == null)
            {
                return HttpNotFound();
            }
            return View(mtb_article);
        }

        //
        // POST: /MTB_Articles/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MTB_Article mtb_article)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mtb_article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mtb_article);
        }

        //
        // GET: /MTB_Articles/Delete/5

        public ActionResult Delete(int id = 0)
        {
            MTB_Article mtb_article = db.MyTecBitsDB.Find(id);
            if (mtb_article == null)
            {
                return HttpNotFound();
            }
            return View(mtb_article);
        }

        //
        // POST: /MTB_Articles/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MTB_Article mtb_article = db.MyTecBitsDB.Find(id);
            db.MyTecBitsDB.Remove(mtb_article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

My-Knockout-Bootstrap-MVC-Sample/Views/MTB_Articles/Create.cshtml
<div class="span12">
    <fieldset>
        <legend>Create Articles</legend>
        <div class="control-group">
            <label class="control-label">Title: </label>
            <div class="controls">
                <input type="text" data-bind="value: Title" placeholder="Article Title" class="input-medium">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Excerpts: </label>
            <div class="controls">
                <textarea data-bind="value: Excerpts" placeholder="Article Excerpts" rows="3"></textarea>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Content: </label>
            <div class="controls">
                <textarea data-bind="value: Content" placeholder="Article Content" rows="6" class="input-xxlarge"></textarea>
            </div>
        </div>
        <div class="control-group">
            <input type="button" value="Save" data-bind="click: btnCreateArticle" class="btn btn-primary" />
            <a href="@Url.Action("", "MTB_Articles")" class="btn btn-primary">Cancel</a>
        </div>
    </fieldset>
</div>
@section Scripts {
   @Scripts.Render("~/Scripts/ViewModel/CreateVM.js")
}

My-Knockout-Bootstrap-MVC-Sample/Views/MTB_Articles/Delete.cshtml
@model MyTecBits_Knockout_Bootstrap_MVC_Sample.Models.MTB_Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>MTB_Article</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Excerpts)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Excerpts)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Content)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

My-Knockout-Bootstrap-MVC-Sample/Views/MTB_Articles/Details.cshtml
@model MyTecBits_Knockout_Bootstrap_MVC_Sample.Models.MTB_Article

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>MTB_Article</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Excerpts)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Excerpts)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Content)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Content)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

My-Knockout-Bootstrap-MVC-Sample/Views/MTB_Articles/Edit.cshtml
@model MyTecBits_Knockout_Bootstrap_MVC_Sample.Models.MTB_Article

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>MTB_Article</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Excerpts)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Excerpts)
            @Html.ValidationMessageFor(model => model.Excerpts)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Content)
            @Html.ValidationMessageFor(model => model.Content)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

My-Knockout-Bootstrap-MVC-Sample/Views/MTB_Articles/Index.cshtml
@{
    ViewBag.Title = "Articles | My Tec Bits";
}
<h2>Articles</h2>
<p>
    <a href="@Url.Action("Create", "MTB_Articles")" class="btn btn-primary btn-large">Create New »</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Excerpts</th>
            <th>Content</th>
        </tr>
    </thead>
    <tbody data-bind="foreach: Articles">
        <tr>
            <td data-bind="text: Title"></td>
            <td data-bind="text: Excerpts"></td>
            <td data-bind="text: Content"></td>
        </tr>
    </tbody>
</table>
@section Scripts {
   @Scripts.Render("~/Scripts/ViewModel/IndexVM.js")
}

My-Knockout-Bootstrap-MVC-Sample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="My Tec Bits - Articles">
    <meta name="author" content="My Tec Bits">
    <!-- Style Sheet Section -->
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container-fluid">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="#">My Tec Bits</a>
                <div class="nav-collapse collapse">
                    <p class="navbar-text pull-right">
                        Logged in as <a href="#" class="navbar-link">Username</a>
                    </p>
                    <ul class="nav">
                        <li class="active"><a href="@Url.Action("", "MTB_Articles")">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span3">
                <div class="well sidebar-nav">
                    <ul class="nav nav-list">
                        <li class="nav-header">Articles</li>
                        <li><a href="@Url.Action("", "MTB_Articles")">Home</a></li>
                        <li><a href="@Url.Action("Create", "MTB_Articles")">Add</a></li>
                        <li class="nav-header">Categories</li>
                        <li><a href="#">Category 1</a></li>
                        <li><a href="#">Category 2</a></li>
                        <li><a href="#">Category 3</a></li>
                    </ul>
                </div>
                <!--/.well -->
            </div>
            <!--/span-->
            <div class="span9">
                <div class="row-fluid"><br />
                @RenderBody()
                    </div>
            </div>
            <!--/span-->
        </div>
        <!--/row-->
        <hr>
        <footer>
            <p>&copy; MyTecBits.com 2013</p>
        </footer>
    </div><!--/.fluid-container-->
    <!-- javascript Section -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")

    @RenderSection("scripts", required: false)
</body>
</html>